#ifndef QIMAGEVIEW_GLOBAL_H
#define QIMAGEVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QIMAGEVIEW_LIBRARY)
#  define QIMAGEVIEW_EXPORT Q_DECL_EXPORT
#else
#  define QIMAGEVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // QIMAGEVIEW_GLOBAL_H
