#ifndef IMAGEVIEWERPLUGIN_GLOBAL_H
#define IMAGEVIEWERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEVIEWERPLUGIN_LIBRARY)
#  define IMAGEVIEWERPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEVIEWERPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEVIEWERPLUGIN_GLOBAL_H
