#ifndef HELLOWORLDPLUGIN_GLOBAL_H
#define HELLOWORLDPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HELLOWORLDPLUGIN_LIBRARY)
#  define HELLOWORLDPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define HELLOWORLDPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // HELLOWORLDPLUGIN_GLOBAL_H
