#ifndef MAINWINDOWPLUGIN_GLOBAL_H
#define MAINWINDOWPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MAINWINDOWPLUGIN_LIBRARY)
#  define MAINWINDOWPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define MAINWINDOWPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // MAINWINDOWPLUGIN_GLOBAL_H
