#ifndef FILEMANAGER_GLOBAL_H
#define FILEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILEMANAGERPLUGIN_LIBRARY)
#  define FILEMANAGERPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define FILEMANAGERPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEMANAGER_GLOBAL_H
