#ifndef WEBVIEWPLUGIN_GLOBAL_H
#define WEBVIEWPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBVIEWPLUGIN_LIBRARY)
#  define WEBVIEWPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define WEBVIEWPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBVIEWPLUGIN_GLOBAL_H
